import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const vehicleModels = [
  { brand: 'Abarth', modelName: '124 Spider' },
  { brand: 'Abarth', modelName: '595' },
  { brand: 'Abarth', modelName: '695' },
  { brand: 'Abarth', modelName: 'Grande Punto' },
  { brand: 'Abarth', modelName: 'Punto Evo' },
  { brand: 'Acura', modelName: 'CL' },
  { brand: 'Acura', modelName: 'ILX' },
  { brand: 'Acura', modelName: 'Integra' },
  { brand: 'Acura', modelName: 'Legend' },
  { brand: 'Acura', modelName: 'MDX' },
  { brand: 'Acura', modelName: 'NSX' },
  { brand: 'Acura', modelName: 'RDX' },
  { brand: 'Acura', modelName: 'RL' },
  { brand: 'Acura', modelName: 'RLX' },
  { brand: 'Acura', modelName: 'RSX' },
  { brand: 'Acura', modelName: 'TL' },
  { brand: 'Acura', modelName: 'TLX' },
  { brand: 'Acura', modelName: 'TSX' },
  { brand: 'Acura', modelName: 'ZDX' },
  { brand: 'Aixam', modelName: 'A.7XX' },
  { brand: 'Aixam', modelName: 'Crossline' },
  { brand: 'Aixam', modelName: 'City' },
  { brand: 'Aixam', modelName: 'Coupe' },
  { brand: 'Aixam', modelName: 'Crossover' },
  { brand: 'Aixam', modelName: 'GTO' },
  { brand: 'Alfa Romeo', modelName: '145' },
  { brand: 'Alfa Romeo', modelName: '146' },
  { brand: 'Alfa Romeo', modelName: '147' },
  { brand: 'Alfa Romeo', modelName: '155' },
  { brand: 'Alfa Romeo', modelName: '156' },
  { brand: 'Alfa Romeo', modelName: '159' },
  { brand: 'Alfa Romeo', modelName: '164' },
  { brand: 'Alfa Romeo', modelName: '166' },
  { brand: 'Alfa Romeo', modelName: '4C' },
  { brand: 'Alfa Romeo', modelName: '8C Competizione' },
  { brand: 'Alfa Romeo', modelName: 'Brera' },
  { brand: 'Alfa Romeo', modelName: 'Giulia' },
  { brand: 'Alfa Romeo', modelName: 'Giulietta' },
  { brand: 'Alfa Romeo', modelName: 'GT' },
  { brand: 'Alfa Romeo', modelName: 'GTV' },
  { brand: 'Alfa Romeo', modelName: 'MiTo' },
  { brand: 'Alfa Romeo', modelName: 'Spider' },
  { brand: 'Alfa Romeo', modelName: 'Stelvio' },
  { brand: 'Alfa Romeo', modelName: 'Tonale' },
  { brand: 'Asia', modelName: 'Rocsta' },
  { brand: 'Asia', modelName: 'Retona' },
  { brand: 'Asia', modelName: 'Topic' },
  { brand: 'Alpine', modelName: 'A110' },
  { brand: 'Alpine', modelName: 'A310' },
  { brand: 'Alpine', modelName: 'A610' },
  { brand: 'Alpine', modelName: 'GTA' },
  { brand: 'Aston Martin', modelName: 'DB7' },
  { brand: 'Aston Martin', modelName: 'DB9' },
  { brand: 'Aston Martin', modelName: 'DB11' },
  { brand: 'Aston Martin', modelName: 'DBS' },
  { brand: 'Aston Martin', modelName: 'Rapide' },
  { brand: 'Aston Martin', modelName: 'Vanquish' },
  { brand: 'Aston Martin', modelName: 'Vantage' },
  { brand: 'Aston Martin', modelName: 'Virage' },
  { brand: 'Aston Martin', modelName: 'Vulcan' },
  { brand: 'Audi', modelName: '80' },
  { brand: 'Audi', modelName: '100' },
  { brand: 'Audi', modelName: '200' },
  { brand: 'Audi', modelName: 'A1' },
  { brand: 'Audi', modelName: 'A2' },
  { brand: 'Audi', modelName: 'A3' },
  { brand: 'Audi', modelName: 'A4' },
  { brand: 'Audi', modelName: 'A5' },
  { brand: 'Audi', modelName: 'A6' },
  { brand: 'Audi', modelName: 'A7' },
  { brand: 'Audi', modelName: 'A8' },
  { brand: 'Audi', modelName: 'Allroad' },
  { brand: 'Audi', modelName: 'E-tron' },
  { brand: 'Audi', modelName: 'Q2' },
  { brand: 'Audi', modelName: 'Q3' },
  { brand: 'Audi', modelName: 'Q5' },
  { brand: 'Audi', modelName: 'Q7' },
  { brand: 'Audi', modelName: 'Q8' },
  { brand: 'Audi', modelName: 'R8' },
  { brand: 'Audi', modelName: 'RS2' },
  { brand: 'Audi', modelName: 'RS3' },
  { brand: 'Audi', modelName: 'RS4' },
  { brand: 'Audi', modelName: 'RS5' },
  { brand: 'Audi', modelName: 'RS6' },
  { brand: 'Audi', modelName: 'RS7' },
  { brand: 'Audi', modelName: 'RSQ3' },
  { brand: 'Audi', modelName: 'S1' },
  { brand: 'Audi', modelName: 'S2' },
  { brand: 'Audi', modelName: 'S3' },
  { brand: 'Audi', modelName: 'S4' },
  { brand: 'Audi', modelName: 'S5' },
  { brand: 'Audi', modelName: 'S6' },
  { brand: 'Audi', modelName: 'S7' },
  { brand: 'Audi', modelName: 'S8' },
  { brand: 'Audi', modelName: 'SQ5' },
  { brand: 'Audi', modelName: 'SQ7' },
  { brand: 'Audi', modelName: 'TT' },
  { brand: 'Audi', modelName: 'Q4' },
  { brand: 'Austin', modelName: 'A30' },
  { brand: 'Austin', modelName: 'A35' },
  { brand: 'Austin', modelName: 'A40' },
  { brand: 'Austin', modelName: 'Allegro' },
  { brand: 'Austin', modelName: 'Ambassador' },
  { brand: 'Austin', modelName: 'Healey 100' },
  { brand: 'Austin', modelName: 'Healey 3000' },
  { brand: 'Austin', modelName: 'Maxi' },
  { brand: 'Austin', modelName: 'Metro' },
  { brand: 'Austin', modelName: 'Mini' },
  { brand: 'Austin', modelName: 'Montego' },
  { brand: 'Austin', modelName: 'Princess' },
  { brand: 'Austin', modelName: 'Rover' },
  { brand: 'Austin', modelName: 'Seven' },
  { brand: 'Autobianchi', modelName: 'A112' },
  { brand: 'Autobianchi', modelName: 'Bianchina' },
  { brand: 'Autobianchi', modelName: 'Primula' },
  { brand: 'Autobianchi', modelName: 'Stellina' },
  { brand: 'Autobianchi', modelName: 'Y10' },
  { brand: 'Baic', modelName: 'BJ20' },
  { brand: 'Baic', modelName: 'BJ40' },
  { brand: 'Baic', modelName: 'BJ80' },
  { brand: 'Baic', modelName: 'EU5' },
  { brand: 'Baic', modelName: 'Senova D50' },
  { brand: 'Baic', modelName: 'Senova D70' },
  { brand: 'Baic', modelName: 'Senova X25' },
  { brand: 'Baic', modelName: 'Senova X55' },
  { brand: 'Baic', modelName: 'X3' },
  { brand: 'Baic', modelName: 'X424' },
  { brand: 'Bentley', modelName: 'Arnage' },
  { brand: 'Bentley', modelName: 'Azure' },
  { brand: 'Bentley', modelName: 'Bentayga' },
  { brand: 'Bentley', modelName: 'Brooklands' },
  { brand: 'Bentley', modelName: 'Continental' },
  { brand: 'Bentley', modelName: 'Flying Spur' },
  { brand: 'Bentley', modelName: 'Mulsanne' },
  { brand: 'BMW', modelName: 'Seria 1' },
  { brand: 'BMW', modelName: 'Seria 1M' },
  { brand: 'BMW', modelName: 'Seria 2' },
  { brand: 'BMW', modelName: 'Seria 2 Active Tourer' },
  { brand: 'BMW', modelName: 'Seria 3' },
  { brand: 'BMW', modelName: 'Seria 4' },
  { brand: 'BMW', modelName: 'Seria 5' },
  { brand: 'BMW', modelName: 'Seria 6' },
  { brand: 'BMW', modelName: 'Seria 7' },
  { brand: 'BMW', modelName: 'Seria 8' },
  { brand: 'BMW', modelName: 'I3' },
  { brand: 'BMW', modelName: 'I8' },
  { brand: 'BMW', modelName: 'M2' },
  { brand: 'BMW', modelName: 'M3' },
  { brand: 'BMW', modelName: 'M4' },
  { brand: 'BMW', modelName: 'M5' },
  { brand: 'BMW', modelName: 'M6' },
  { brand: 'BMW', modelName: 'X1' },
  { brand: 'BMW', modelName: 'X2' },
  { brand: 'BMW', modelName: 'X3' },
  { brand: 'BMW', modelName: 'X3 M' },
  { brand: 'BMW', modelName: 'X4' },
  { brand: 'BMW', modelName: 'X4 M' },
  { brand: 'BMW', modelName: 'X5' },
  { brand: 'BMW', modelName: 'X5 M' },
  { brand: 'BMW', modelName: 'X6' },
  { brand: 'BMW', modelName: 'X6 M' },
  { brand: 'BMW', modelName: 'X7' },
  { brand: 'BMW', modelName: 'Z3' },
  { brand: 'BMW', modelName: 'Z3 M' },
  { brand: 'BMW', modelName: 'Z4' },
  { brand: 'BMW', modelName: 'Z4 M' },
  { brand: 'BMW', modelName: '5 GT' },
  { brand: 'BMW-ALPINA', modelName: 'B3' },
  { brand: 'BMW-ALPINA', modelName: 'B4' },
  { brand: 'BMW-ALPINA', modelName: 'B5' },
  { brand: 'BMW-ALPINA', modelName: 'B6' },
  { brand: 'BMW-ALPINA', modelName: 'B7' },
  { brand: 'BMW-ALPINA', modelName: 'D3' },
  { brand: 'BMW-ALPINA', modelName: 'D5' },
  { brand: 'BMW-ALPINA', modelName: 'XD3' },
  { brand: 'BMW-ALPINA', modelName: 'XD4' },
  { brand: 'Brilliance', modelName: 'BS2' },
  { brand: 'Brilliance', modelName: 'BS4' },
  { brand: 'Brilliance', modelName: 'BS6' },
  { brand: 'Brilliance', modelName: 'FRV' },
  { brand: 'Brilliance', modelName: 'H230' },
  { brand: 'Brilliance', modelName: 'H530' },
  { brand: 'Brilliance', modelName: 'M1' },
  { brand: 'Brilliance', modelName: 'M2' },
  { brand: 'Brilliance', modelName: 'V3' },
  { brand: 'Brilliance', modelName: 'V5' },
  { brand: 'Bugatti', modelName: 'Chiron' },
  { brand: 'Bugatti', modelName: 'Divo' },
  { brand: 'Bugatti', modelName: 'EB110' },
  { brand: 'Bugatti', modelName: 'La Voiture Noire' },
  { brand: 'Bugatti', modelName: 'Veyron' },
  { brand: 'Buick', modelName: 'Cascada' },
  { brand: 'Buick', modelName: 'Enclave' },
  { brand: 'Buick', modelName: 'Encore' },
  { brand: 'Buick', modelName: 'Envision' },
  { brand: 'Buick', modelName: 'LaCrosse' },
  { brand: 'Buick', modelName: 'LeSabre' },
  { brand: 'Buick', modelName: 'Lucerne' },
  { brand: 'Buick', modelName: 'Park Avenue' },
  { brand: 'Buick', modelName: 'Regal' },
  { brand: 'Buick', modelName: 'Riviera' },
  { brand: 'Buick', modelName: 'Roadmaster' },
  { brand: 'Buick', modelName: 'Verano' },
  { brand: 'Cadillac', modelName: 'ATS' },
  { brand: 'Cadillac', modelName: 'CT4' },
  { brand: 'Cadillac', modelName: 'CT5' },
  { brand: 'Cadillac', modelName: 'CT6' },
  { brand: 'Cadillac', modelName: 'CTS' },
  { brand: 'Cadillac', modelName: 'DeVille' },
  { brand: 'Cadillac', modelName: 'Eldorado' },
  { brand: 'Cadillac', modelName: 'Escalade' },
  { brand: 'Cadillac', modelName: 'Lyriq' },
  { brand: 'Cadillac', modelName: 'Seville' },
  { brand: 'Cadillac', modelName: 'SRX' },
  { brand: 'Cadillac', modelName: 'XT4' },
  { brand: 'Cadillac', modelName: 'XT5' },
  { brand: 'Cadillac', modelName: 'XT6' },
  { brand: 'Casalini', modelName: 'M10' },
  { brand: 'Casalini', modelName: 'M14' },
  { brand: 'Casalini', modelName: 'Sulky' },
  { brand: 'Casalini', modelName: 'Ydea' },
  { brand: 'Caterham', modelName: 'Seven 160' },
  { brand: 'Caterham', modelName: 'Seven 270' },
  { brand: 'Caterham', modelName: 'Seven 310' },
  { brand: 'Caterham', modelName: 'Seven 360' },
  { brand: 'Caterham', modelName: 'Seven 420' },
  { brand: 'Caterham', modelName: 'Seven 620' },
  { brand: 'Chatenet', modelName: 'CH26' },
  { brand: 'Chatenet', modelName: 'CH30' },
  { brand: 'Chatenet', modelName: 'CH40' },
  { brand: 'Chatenet', modelName: 'CH46' },
  { brand: 'Chatenet', modelName: 'Speedino' },
  { brand: 'Chevrolet', modelName: 'Aveo' },
  { brand: 'Chevrolet', modelName: 'Blazer' },
  { brand: 'Chevrolet', modelName: 'Bolt EV' },
  { brand: 'Chevrolet', modelName: 'Camaro' },
  { brand: 'Chevrolet', modelName: 'Captiva' },
  { brand: 'Chevrolet', modelName: 'Cavalier' },
  { brand: 'Chevrolet', modelName: 'Chevelle' },
  { brand: 'Chevrolet', modelName: 'Colorado' },
  { brand: 'Chevrolet', modelName: 'Corvette' },
  { brand: 'Chevrolet', modelName: 'Cruze' },
  { brand: 'Chevrolet', modelName: 'Equinox' },
  { brand: 'Chevrolet', modelName: 'Impala' },
  { brand: 'Chevrolet', modelName: 'Malibu' },
  { brand: 'Chevrolet', modelName: 'Silverado' },
  { brand: 'Chevrolet', modelName: 'Spark' },
  { brand: 'Chevrolet', modelName: 'Suburban' },
  { brand: 'Chevrolet', modelName: 'Tahoe' },
  { brand: 'Chevrolet', modelName: 'Trailblazer' },
  { brand: 'Chevrolet', modelName: 'Traverse' },
  { brand: 'Chevrolet', modelName: 'Trax' },
  { brand: 'Chrysler', modelName: '200' },
  { brand: 'Chrysler', modelName: '300' },
  { brand: 'Chrysler', modelName: '300C' },
  { brand: 'Chrysler', modelName: 'Aspen' },
  { brand: 'Chrysler', modelName: 'Crossfire' },
  { brand: 'Chrysler', modelName: 'Pacifica' },
  { brand: 'Chrysler', modelName: 'PT Cruiser' },
  { brand: 'Chrysler', modelName: 'Sebring' },
  { brand: 'Chrysler', modelName: 'Voyager' },
  { brand: 'Citroen', modelName: '2CV' },
  { brand: 'Citroen', modelName: 'Berlingo' },
  { brand: 'Citroen', modelName: 'C-Crosser' },
  { brand: 'Citroen', modelName: 'C-Elysee' },
  { brand: 'Citroen', modelName: 'C1' },
  { brand: 'Citroen', modelName: 'C2' },
  { brand: 'Citroen', modelName: 'C3' },
  { brand: 'Citroen', modelName: 'C3 AirCross' },
  { brand: 'Citroen', modelName: 'C3 Picasso' },
  { brand: 'Citroen', modelName: 'C4' },
  { brand: 'Citroen', modelName: 'C4 AirCross' },
  { brand: 'Citroen', modelName: 'C4 Picasso' },
  { brand: 'Citroen', modelName: 'C4 Spacetourer' },
  { brand: 'Citroen', modelName: 'C4 Cactus' },
  { brand: 'Citroen', modelName: 'C5' },
  { brand: 'Citroen', modelName: 'C5 AirCross' },
  { brand: 'Citroen', modelName: 'C6' },
  { brand: 'Citroen', modelName: 'C8' },
  { brand: 'Citroen', modelName: 'DS3' },
  { brand: 'Citroen', modelName: 'DS4' },
  { brand: 'Citroen', modelName: 'DS5' },
  { brand: 'Citroen', modelName: 'E-Mehari' },
  { brand: 'Citroen', modelName: 'Evasion' },
  { brand: 'Citroen', modelName: 'Jumpy' },
  { brand: 'Citroen', modelName: 'Saxo' },
  { brand: 'Citroen', modelName: 'SpaceTourer' },
  { brand: 'Citroen', modelName: 'Xantia' },
  { brand: 'Citroen', modelName: 'XM' },
  { brand: 'Citroen', modelName: 'Xsara' },
  { brand: 'Citroen', modelName: 'Xsara Picasso' },
  { brand: 'Citroen', modelName: 'C5X' },
  { brand: 'Cupra', modelName: 'Ateca' },
  { brand: 'Cupra', modelName: 'Born' },
  { brand: 'Cupra', modelName: 'Formentor' },
  { brand: 'Cupra', modelName: 'Leon' },
  { brand: 'Cupra', modelName: 'Tavascan' },
  { brand: 'Dacia', modelName: 'Dokker' },
  { brand: 'Dacia', modelName: 'Duster' },
  { brand: 'Dacia', modelName: 'Lodgy' },
  { brand: 'Dacia', modelName: 'Logan' },
  { brand: 'Dacia', modelName: 'Sandero' },
  { brand: 'Dacia', modelName: 'Spring' },
  { brand: 'Daewoo', modelName: 'Espero' },
  { brand: 'Daewoo', modelName: 'Kalos' },
  { brand: 'Daewoo', modelName: 'Lacetti' },
  { brand: 'Daewoo', modelName: 'Lanos' },
  { brand: 'Daewoo', modelName: 'Leganza' },
  { brand: 'Daewoo', modelName: 'Matiz' },
  { brand: 'Daewoo', modelName: 'Nexia' },
  { brand: 'Daewoo', modelName: 'Nubira' },
  { brand: 'Daewoo', modelName: 'Tacuma' },
  { brand: 'Daihatsu', modelName: 'Applause' },
  { brand: 'Daihatsu', modelName: 'Charade' },
  { brand: 'Daihatsu', modelName: 'Copen' },
  { brand: 'Daihatsu', modelName: 'Cuore' },
  { brand: 'Daihatsu', modelName: 'Feroza' },
  { brand: 'Daihatsu', modelName: 'Gran Move' },
  { brand: 'Daihatsu', modelName: 'Materia' },
  { brand: 'Daihatsu', modelName: 'Move' },
  { brand: 'Daihatsu', modelName: 'Rocky' },
  { brand: 'Daihatsu', modelName: 'Sirion' },
  { brand: 'Daihatsu', modelName: 'Terios' },
  { brand: 'Daihatsu', modelName: 'Trevis' },
  { brand: 'Daihatsu', modelName: 'YRV' },
  { brand: 'DeLorean', modelName: 'DMC-12' },
  { brand: 'DFM', modelName: 'Fengon 580' },
  { brand: 'DFM', modelName: 'Fengon ix5' },
  { brand: 'DFM', modelName: 'Fengshen AX7' },
  { brand: 'DFM', modelName: 'Glory 580' },
  { brand: 'DKW', modelName: 'F102' },
  { brand: 'DKW', modelName: 'Junior' },
  { brand: 'DKW', modelName: 'Munga' },
  { brand: 'Dodge', modelName: 'Avenger' },
  { brand: 'Dodge', modelName: 'Caliber' },
  { brand: 'Dodge', modelName: 'Challenger' },
  { brand: 'Dodge', modelName: 'Charger' },
  { brand: 'Dodge', modelName: 'Dart' },
  { brand: 'Dodge', modelName: 'Durango' },
  { brand: 'Dodge', modelName: 'Journey' },
  { brand: 'Dodge', modelName: 'Neon' },
  { brand: 'Dodge', modelName: 'Nitro' },
  { brand: 'Dodge', modelName: 'Ram' },
  { brand: 'Dodge', modelName: 'Viper' },
  { brand: 'DS Automobiles', modelName: 'DS3' },
  { brand: 'DS Automobiles', modelName: 'DS4' },
  { brand: 'DS Automobiles', modelName: 'DS5' },
  { brand: 'DS Automobiles', modelName: 'DS7 Crossback' },
  { brand: 'DS Automobiles', modelName: 'DS9' },
  { brand: 'Elaris', modelName: 'Beo' },
  { brand: 'Elaris', modelName: 'Finn' },
  { brand: 'Elaris', modelName: 'Leo' },
  { brand: 'FAW', modelName: 'Besturn B30' },
  { brand: 'FAW', modelName: 'Besturn B50' },
  { brand: 'FAW', modelName: 'Besturn B70' },
  { brand: 'FAW', modelName: 'Besturn X40' },
  { brand: 'FAW', modelName: 'Besturn X80' },
  { brand: 'FAW', modelName: 'Hongqi H5' },
  { brand: 'FAW', modelName: 'Hongqi H7' },
  { brand: 'FAW', modelName: 'Hongqi L5' },
  { brand: 'Ferrari', modelName: '488 GTB' },
  { brand: 'Ferrari', modelName: '488 Pista' },
  { brand: 'Ferrari', modelName: '812 Superfast' },
  { brand: 'Ferrari', modelName: 'California' },
  { brand: 'Ferrari', modelName: 'Enzo' },
  { brand: 'Ferrari', modelName: 'F12 Berlinetta' },
  { brand: 'Ferrari', modelName: 'F40' },
  { brand: 'Ferrari', modelName: 'F430' },
  { brand: 'Ferrari', modelName: 'F8 Tributo' },
  { brand: 'Ferrari', modelName: 'GTC4Lusso' },
  { brand: 'Ferrari', modelName: 'LaFerrari' },
  { brand: 'Ferrari', modelName: 'Portofino' },
  { brand: 'Ferrari', modelName: 'Roma' },
  { brand: 'Ferrari', modelName: 'SF90 Stradale' },
  { brand: 'Fiat', modelName: '124 Spider' },
  { brand: 'Fiat', modelName: '126' },
  { brand: 'Fiat', modelName: '127' },
  { brand: 'Fiat', modelName: '500' },
  { brand: 'Fiat', modelName: '500L' },
  { brand: 'Fiat', modelName: 'Albea' },
  { brand: 'Fiat', modelName: 'Barchetta' },
  { brand: 'Fiat', modelName: 'Brava' },
  { brand: 'Fiat', modelName: 'Bravo' },
  { brand: 'Fiat', modelName: 'Cinquecento' },
  { brand: 'Fiat', modelName: 'Coupe' },
  { brand: 'Fiat', modelName: 'Croma' },
  { brand: 'Fiat', modelName: 'Dino' },
  { brand: 'Fiat', modelName: 'Doblo' },
  { brand: 'Fiat', modelName: 'Fiorino' },
  { brand: 'Fiat', modelName: 'Freemont' },
  { brand: 'Fiat', modelName: 'Fullback' },
  { brand: 'Fiat', modelName: 'Grande Punto' },
  { brand: 'Fiat', modelName: 'Linea' },
  { brand: 'Fiat', modelName: 'Marea' },
  { brand: 'Fiat', modelName: 'Multipla' },
  { brand: 'Fiat', modelName: 'Palio' },
  { brand: 'Fiat', modelName: 'Panda' },
  { brand: 'Fiat', modelName: 'Punto' },
  { brand: 'Fiat', modelName: 'Scudo' },
  { brand: 'Fiat', modelName: 'Sedici' },
  { brand: 'Fiat', modelName: 'Siena' },
  { brand: 'Fiat', modelName: 'Stilo' },
  { brand: 'Fiat', modelName: 'Tempra' },
  { brand: 'Fiat', modelName: 'Tipo' },
  { brand: 'Fiat', modelName: 'Ulysse' },
  { brand: 'Fiat', modelName: 'Uno' },
  { brand: 'Fiat', modelName: '500X' },
  { brand: 'Fiat', modelName: 'Seicento' },
  { brand: 'Ford', modelName: 'Bronco' },
  { brand: 'Ford', modelName: 'B-Max' },
  { brand: 'Ford', modelName: 'C-Max' },
  { brand: 'Ford', modelName: 'Cortina' },
  { brand: 'Ford', modelName: 'Cougar' },
  { brand: 'Ford', modelName: 'Crown Victoria' },
  { brand: 'Ford', modelName: 'EcoSport' },
  { brand: 'Ford', modelName: 'Edge' },
  { brand: 'Ford', modelName: 'Escape' },
  { brand: 'Ford', modelName: 'Escort' },
  { brand: 'Ford', modelName: 'Expedition' },
  { brand: 'Ford', modelName: 'Explorer' },
  { brand: 'Ford', modelName: 'F-150' },
  { brand: 'Ford', modelName: 'Fiesta' },
  { brand: 'Ford', modelName: 'Focus' },
  { brand: 'Ford', modelName: 'Fusion' },
  { brand: 'Ford', modelName: 'Galaxy' },
  { brand: 'Ford', modelName: 'GT' },
  { brand: 'Ford', modelName: 'Ka' },
  { brand: 'Ford', modelName: 'Kuga' },
  { brand: 'Ford', modelName: 'Maverick' },
  { brand: 'Ford', modelName: 'Mondeo' },
  { brand: 'Ford', modelName: 'Mustang' },
  { brand: 'Ford', modelName: 'Probe' },
  { brand: 'Ford', modelName: 'Puma' },
  { brand: 'Ford', modelName: 'Ranger' },
  { brand: 'Ford', modelName: 'S-Max' },
  { brand: 'Ford', modelName: 'Scorpio' },
  { brand: 'Ford', modelName: 'Street KA' },
  { brand: 'Ford', modelName: 'Taurus' },
  { brand: 'Ford', modelName: 'Thunderbird' },
  { brand: 'Ford', modelName: 'Tourneo' },
  { brand: 'Ford', modelName: 'Tourneo Connect' },
  { brand: 'Ford', modelName: 'Tourneo Custom' },
  { brand: 'Ford', modelName: 'Transit' },
  { brand: 'Ford', modelName: 'Transit Connect' },
  { brand: 'Ford', modelName: 'Windstar' },
  { brand: 'Gaz', modelName: '31029 Volga' },
  { brand: 'Gaz', modelName: '3110 Volga' },
  { brand: 'Gaz', modelName: '69' },
  { brand: 'Gaz', modelName: 'M20 Pobeda' },
  { brand: 'Gaz', modelName: 'M21 Volga' },
  { brand: 'Gaz', modelName: 'M24 Volga' },
  { brand: 'Geely', modelName: 'Atlas' },
  { brand: 'Geely', modelName: 'Emgrand 7' },
  { brand: 'Geely', modelName: 'Emgrand EC7' },
  { brand: 'Geely', modelName: 'Emgrand X7' },
  { brand: 'Geely', modelName: 'GC9' },
  { brand: 'Geely', modelName: 'MK' },
  { brand: 'Geely', modelName: 'MK Cross' },
  { brand: 'Geely', modelName: 'Panda' },
  { brand: 'Genesis', modelName: 'G70' },
  { brand: 'Genesis', modelName: 'G80' },
  { brand: 'Genesis', modelName: 'G90' },
  { brand: 'Genesis', modelName: 'GV70' },
  { brand: 'Genesis', modelName: 'GV80' },
  { brand: 'GMC', modelName: 'Acadia' },
  { brand: 'GMC', modelName: 'Canyon' },
  { brand: 'GMC', modelName: 'Envoy' },
  { brand: 'GMC', modelName: 'Savana' },
  { brand: 'GMC', modelName: 'Sierra 1500' },
  { brand: 'GMC', modelName: 'Sierra 2500HD' },
  { brand: 'GMC', modelName: 'Terrain' },
  { brand: 'GMC', modelName: 'Yukon' },
  { brand: 'GWM', modelName: 'Cannon' },
  { brand: 'GWM', modelName: 'Haval H6' },
  { brand: 'GWM', modelName: 'Haval Jolion' },
  { brand: 'GWM', modelName: 'P Series' },
  { brand: 'GWM', modelName: 'Poer' },
  { brand: 'GWM', modelName: 'Steed 5' },
  { brand: 'GWM', modelName: 'Steed 6' },
  { brand: 'Honda', modelName: 'Accord' },
  { brand: 'Honda', modelName: 'City' },
  { brand: 'Honda', modelName: 'Civic' },
  { brand: 'Honda', modelName: 'Concerto' },
  { brand: 'Honda', modelName: 'BR-V' },
  { brand: 'Honda', modelName: 'CR-V' },
  { brand: 'Honda', modelName: 'CR-X' },
  { brand: 'Honda', modelName: 'CR-Z' },
  { brand: 'Honda', modelName: 'E' },
  { brand: 'Honda', modelName: 'Element' },
  { brand: 'Honda', modelName: 'Fit' },
  { brand: 'Honda', modelName: 'FR-V' },
  { brand: 'Honda', modelName: 'HR-V' },
  { brand: 'Honda', modelName: 'Insight' },
  { brand: 'Honda', modelName: 'Integra' },
  { brand: 'Honda', modelName: 'Jazz' },
  { brand: 'Honda', modelName: 'Legend' },
  { brand: 'Honda', modelName: 'NSX' },
  { brand: 'Honda', modelName: 'Odyssey' },
  { brand: 'Honda', modelName: 'Passport' },
  { brand: 'Honda', modelName: 'Pilot' },
  { brand: 'Honda', modelName: 'Prelude' },
  { brand: 'Honda', modelName: 'S2000' },
  { brand: 'Honda', modelName: 'Ridgeline' },
  { brand: 'Honda', modelName: 'Shuttle' },
  { brand: 'Honda', modelName: 'Z-RV' },
  { brand: 'Hongqi', modelName: 'E-HS3' },
  { brand: 'Hongqi', modelName: 'E-HS9' },
  { brand: 'Hongqi', modelName: 'H5' },
  { brand: 'Hongqi', modelName: 'H7' },
  { brand: 'Hongqi', modelName: 'L5' },
  { brand: 'Hongqi', modelName: 'S9' },
  { brand: 'Hummer', modelName: 'H1' },
  { brand: 'Hummer', modelName: 'H2' },
  { brand: 'Hummer', modelName: 'H3' },
  { brand: 'Hyundai', modelName: 'Accent' },
  { brand: 'Hyundai', modelName: 'Atos' },
  { brand: 'Hyundai', modelName: 'Coupe' },
  { brand: 'Hyundai', modelName: 'Creta' },
  { brand: 'Hyundai', modelName: 'Elantra' },
  { brand: 'Hyundai', modelName: 'Galloper' },
  { brand: 'Hyundai', modelName: 'Genesis' },
  { brand: 'Hyundai', modelName: 'Getz' },
  { brand: 'Hyundai', modelName: 'H-1' },
  { brand: 'Hyundai', modelName: 'Grand I10' },
  { brand: 'Hyundai', modelName: 'I10' },
  { brand: 'Hyundai', modelName: 'I20' },
  { brand: 'Hyundai', modelName: 'I30' },
  { brand: 'Hyundai', modelName: 'I40' },
  { brand: 'Hyundai', modelName: 'I45' },
  { brand: 'Hyundai', modelName: 'Ioniq' },
  { brand: 'Hyundai', modelName: 'Ix20' },
  { brand: 'Hyundai', modelName: 'Ix35' },
  { brand: 'Hyundai', modelName: 'Kona' },
  { brand: 'Hyundai', modelName: 'Matrix' },
  { brand: 'Hyundai', modelName: 'Santa Fe' },
  { brand: 'Hyundai', modelName: 'Sonata' },
  { brand: 'Hyundai', modelName: 'Terracan' },
  { brand: 'Hyundai', modelName: 'Tucson' },
  { brand: 'Hyundai', modelName: 'Veloster' },
  { brand: 'Hyundai', modelName: 'Venue' },
  { brand: 'Hyundai', modelName: 'Veracruz' },
  { brand: 'Ineos', modelName: 'Grenadier' },
  { brand: 'Infinity', modelName: 'EX' },
  { brand: 'Infinity', modelName: 'FX' },
  { brand: 'Infinity', modelName: 'G' },
  { brand: 'Infinity', modelName: 'I' },
  { brand: 'Infinity', modelName: 'JX' },
  { brand: 'Infinity', modelName: 'M' },
  { brand: 'Infinity', modelName: 'Q30' },
  { brand: 'Infinity', modelName: 'Q50' },
  { brand: 'Infinity', modelName: 'Q60' },
  { brand: 'Infinity', modelName: 'Q70' },
  { brand: 'Infinity', modelName: 'QX' },
  { brand: 'Infinity', modelName: 'QX30' },
  { brand: 'Infinity', modelName: 'QX50' },
  { brand: 'Infinity', modelName: 'QX60' },
  { brand: 'Infinity', modelName: 'QX70' },
  { brand: 'Infinity', modelName: 'QX80' },
  { brand: 'Infinity', modelName: 'G35' },
  { brand: 'Infinity', modelName: 'G37' },
  { brand: 'Isuzu', modelName: 'Axiom' },
  { brand: 'Isuzu', modelName: 'D-Max' },
  { brand: 'Isuzu', modelName: 'Hombre' },
  { brand: 'Isuzu', modelName: 'MU-7' },
  { brand: 'Isuzu', modelName: 'MU-X' },
  { brand: 'Isuzu', modelName: 'Rodeo' },
  { brand: 'Isuzu', modelName: 'Trooper' },
  { brand: 'Isuzu', modelName: 'VehiCROSS' },
  { brand: 'Iveco', modelName: 'Daily' },
  { brand: 'Iveco', modelName: 'EuroCargo' },
  { brand: 'Iveco', modelName: 'EuroTech' },
  { brand: 'Iveco', modelName: 'Massif' },
  { brand: 'Iveco', modelName: 'Stralis' },
  { brand: 'Iveco', modelName: 'Trakker' },
  { brand: 'Jaguar', modelName: 'E-Pace' },
  { brand: 'Jaguar', modelName: 'F-Pace' },
  { brand: 'Jaguar', modelName: 'F-Type' },
  { brand: 'Jaguar', modelName: 'I-Pace' },
  { brand: 'Jaguar', modelName: 'S-Type' },
  { brand: 'Jaguar', modelName: 'X-Type' },
  { brand: 'Jaguar', modelName: 'XE' },
  { brand: 'Jaguar', modelName: 'XF' },
  { brand: 'Jaguar', modelName: 'XJ' },
  { brand: 'Jaguar', modelName: 'XK' },
  { brand: 'Jeep', modelName: 'Cherokee' },
  { brand: 'Jeep', modelName: 'Commander' },
  { brand: 'Jeep', modelName: 'Compass' },
  { brand: 'Jeep', modelName: 'Gladiator' },
  { brand: 'Jeep', modelName: 'Grand Cherokee' },
  { brand: 'Jeep', modelName: 'Liberty' },
  { brand: 'Jeep', modelName: 'Patriot' },
  { brand: 'Jeep', modelName: 'Renegade' },
  { brand: 'Jeep', modelName: 'Wrangler' },
  { brand: 'Kia', modelName: 'Carens' },
  { brand: 'Kia', modelName: 'Carnival' },
  { brand: 'Kia', modelName: 'Ceed' },
  { brand: 'Kia', modelName: 'Cerato' },
  { brand: 'Kia', modelName: 'Clarus' },
  { brand: 'Kia', modelName: 'Magentis' },
  { brand: 'Kia', modelName: 'Niro' },
  { brand: 'Kia', modelName: 'Optima' },
  { brand: 'Kia', modelName: 'Picanto' },
  { brand: 'Kia', modelName: 'Rio' },
  { brand: 'Kia', modelName: 'Sephia' },
  { brand: 'Kia', modelName: 'Shuma' },
  { brand: 'Kia', modelName: 'Sorento' },
  { brand: 'Kia', modelName: 'Soul' },
  { brand: 'Kia', modelName: 'Sportage' },
  { brand: 'Kia', modelName: 'Stinger' },
  { brand: 'Kia', modelName: 'Stonic' },
  { brand: 'Kia', modelName: 'Venga' },
  { brand: 'Kia', modelName: 'Pro`Ceed' },
  { brand: 'KTM', modelName: 'X-Bow' },
  { brand: 'Lada', modelName: '2101' },
  { brand: 'Lada', modelName: '2105' },
  { brand: 'Lada', modelName: '2107' },
  { brand: 'Lada', modelName: '2110' },
  { brand: 'Lada', modelName: 'Granta' },
  { brand: 'Lada', modelName: 'Kalina' },
  { brand: 'Lada', modelName: 'Niva' },
  { brand: 'Lada', modelName: 'Priora' },
  { brand: 'Lada', modelName: 'Vesta' },
  { brand: 'Lada', modelName: 'XRAY' },
  { brand: 'Lamborghini', modelName: 'Aventador' },
  { brand: 'Lamborghini', modelName: 'Centenario' },
  { brand: 'Lamborghini', modelName: 'Countach' },
  { brand: 'Lamborghini', modelName: 'Diablo' },
  { brand: 'Lamborghini', modelName: 'Gallardo' },
  { brand: 'Lamborghini', modelName: 'Huracan' },
  { brand: 'Lamborghini', modelName: 'Murcielago' },
  { brand: 'Lamborghini', modelName: 'Reventon' },
  { brand: 'Lamborghini', modelName: 'Sesto Elemento' },
  { brand: 'Lamborghini', modelName: 'Sian' },
  { brand: 'Lamborghini', modelName: 'Urus' },
  { brand: 'Lancia', modelName: 'Dedra' },
  { brand: 'Lancia', modelName: 'Delta' },
  { brand: 'Lancia', modelName: 'Kappa' },
  { brand: 'Lancia', modelName: 'Lybra' },
  { brand: 'Lancia', modelName: 'Montecarlo' },
  { brand: 'Lancia', modelName: 'Musa' },
  { brand: 'Lancia', modelName: 'Phedra' },
  { brand: 'Lancia', modelName: 'Thema' },
  { brand: 'Lancia', modelName: 'Thesis' },
  { brand: 'Lancia', modelName: 'Y10' },
  { brand: 'Lancia', modelName: 'Ypsilon' },
  { brand: 'Leapmotor', modelName: 'C11' },
  { brand: 'Leapmotor', modelName: 'S01' },
  { brand: 'Leapmotor', modelName: 'T03' },
  { brand: 'LEVC', modelName: 'TX' },
  { brand: 'Land Rover', modelName: 'Defender' },
  { brand: 'Land Rover', modelName: 'Discovery' },
  { brand: 'Land Rover', modelName: 'Discovery Sport' },
  { brand: 'Land Rover', modelName: 'Freelander' },
  { brand: 'Land Rover', modelName: 'Range Rover' },
  { brand: 'Land Rover', modelName: 'Range Rover Evoque' },
  { brand: 'Land Rover', modelName: 'Range Rover Sport' },
  { brand: 'Land Rover', modelName: 'Range Rover Velar' },
  { brand: 'Lexus', modelName: 'CT' },
  { brand: 'Lexus', modelName: 'ES' },
  { brand: 'Lexus', modelName: 'GS' },
  { brand: 'Lexus', modelName: 'IS' },
  { brand: 'Lexus', modelName: 'LC' },
  { brand: 'Lexus', modelName: 'LS' },
  { brand: 'Lexus', modelName: 'LX' },
  { brand: 'Lexus', modelName: 'NX' },
  { brand: 'Lexus', modelName: 'RC' },
  { brand: 'Lexus', modelName: 'RX' },
  { brand: 'Lexus', modelName: 'SC' },
  { brand: 'Lexus', modelName: 'UX' },
  { brand: 'Lexus', modelName: 'RZ' },
  { brand: 'Ligier', modelName: 'JS50' },
  { brand: 'Ligier', modelName: 'JS60' },
  { brand: 'Ligier', modelName: 'JSRC' },
  { brand: 'Lincoln', modelName: 'Aviator' },
  { brand: 'Lincoln', modelName: 'Continental' },
  { brand: 'Lincoln', modelName: 'Corsair' },
  { brand: 'Lincoln', modelName: 'MKC' },
  { brand: 'Lincoln', modelName: 'MKS' },
  { brand: 'Lincoln', modelName: 'MKT' },
  { brand: 'Lincoln', modelName: 'MKX' },
  { brand: 'Lincoln', modelName: 'MKZ' },
  { brand: 'Lincoln', modelName: 'Nautilus' },
  { brand: 'Lincoln', modelName: 'Navigator' },
  { brand: 'Lixiang', modelName: 'One' },
  { brand: 'Lotus', modelName: 'Elise' },
  { brand: 'Lotus', modelName: 'Elan' },
  { brand: 'Lotus', modelName: 'Elite' },
  { brand: 'Lotus', modelName: 'Emira' },
  { brand: 'Lotus', modelName: 'Evora' },
  { brand: 'Lotus', modelName: 'Exige' },
  { brand: 'LTI', modelName: 'TX1' },
  { brand: 'LTI', modelName: 'TX2' },
  { brand: 'LTI', modelName: 'TX4' },
  { brand: 'Lucid', modelName: 'Air' },
  { brand: 'Lynk & Co', modelName: '01' },
  { brand: 'Lynk & Co', modelName: '02' },
  { brand: 'Lynk & Co', modelName: '03' },
  { brand: 'Lynk & Co', modelName: '05' },
  { brand: 'Lynk & Co', modelName: '09' },
  { brand: 'MAN', modelName: 'TGE' },
  { brand: 'Maserati', modelName: '3200 GT' },
  { brand: 'Maserati', modelName: 'Biturbo' },
  { brand: 'Maserati', modelName: 'Ghibli' },
  { brand: 'Maserati', modelName: 'GranCabrio' },
  { brand: 'Maserati', modelName: 'GranTurismo' },
  { brand: 'Maserati', modelName: 'Levante' },
  { brand: 'Maserati', modelName: 'Quattroporte' },
  { brand: 'MAXIMUS', modelName: 'T/C' },
  { brand: 'MAXIMUS', modelName: 'X' },
  { brand: 'Maxus', modelName: 'D90' },
  { brand: 'Maxus', modelName: 'EG10' },
  { brand: 'Maxus', modelName: 'EV30' },
  { brand: 'Maxus', modelName: 'G10' },
  { brand: 'Maxus', modelName: 'G20' },
  { brand: 'Maxus', modelName: 'G50' },
  { brand: 'Maxus', modelName: 'T60' },
  { brand: 'Maybach', modelName: '57' },
  { brand: 'Maybach', modelName: '62' },
  { brand: 'Mazda', modelName: '121' },
  { brand: 'Mazda', modelName: '2' },
  { brand: 'Mazda', modelName: '3' },
  { brand: 'Mazda', modelName: '323' },
  { brand: 'Mazda', modelName: '5' },
  { brand: 'Mazda', modelName: '6' },
  { brand: 'Mazda', modelName: '626' },
  { brand: 'Mazda', modelName: '929' },
  { brand: 'Mazda', modelName: 'B-Series' },
  { brand: 'Mazda', modelName: 'CX-3' },
  { brand: 'Mazda', modelName: 'CX-30' },
  { brand: 'Mazda', modelName: 'CX-5' },
  { brand: 'Mazda', modelName: 'CX-7' },
  { brand: 'Mazda', modelName: 'CX-9' },
  { brand: 'Mazda', modelName: 'Demio' },
  { brand: 'Mazda', modelName: 'MPV' },
  { brand: 'Mazda', modelName: 'MX-3' },
  { brand: 'Mazda', modelName: 'MX-5' },
  { brand: 'Mazda', modelName: 'MX-6' },
  { brand: 'Mazda', modelName: 'Premacy' },
  { brand: 'Mazda', modelName: 'RX-7' },
  { brand: 'Mazda', modelName: 'RX-8' },
  { brand: 'Mazda', modelName: 'Tribute' },
  { brand: 'Mazda', modelName: 'Xedos' },
  { brand: 'McLaren', modelName: '540C' },
  { brand: 'McLaren', modelName: '570GT' },
  { brand: 'McLaren', modelName: '570S' },
  { brand: 'McLaren', modelName: '600LT' },
  { brand: 'McLaren', modelName: '620R' },
  { brand: 'McLaren', modelName: '650S' },
  { brand: 'McLaren', modelName: '675LT' },
  { brand: 'McLaren', modelName: '720S' },
  { brand: 'McLaren', modelName: '750S' },
  { brand: 'McLaren', modelName: '765LT' },
  { brand: 'McLaren', modelName: 'P1' },
  { brand: 'McLaren', modelName: 'Senna' },
  { brand: 'Mercedes-Benz', modelName: 'A-Class' },
  { brand: 'Mercedes-Benz', modelName: 'AMG GT' },
  { brand: 'Mercedes-Benz', modelName: 'B-Class' },
  { brand: 'Mercedes-Benz', modelName: 'C-Class' },
  { brand: 'Mercedes-Benz', modelName: 'Citan' },
  { brand: 'Mercedes-Benz', modelName: 'CL' },
  { brand: 'Mercedes-Benz', modelName: 'CLA' },
  { brand: 'Mercedes-Benz', modelName: 'CLC' },
  { brand: 'Mercedes-Benz', modelName: 'CLK' },
  { brand: 'Mercedes-Benz', modelName: 'CLS' },
  { brand: 'Mercedes-Benz', modelName: 'E-Class' },
  { brand: 'Mercedes-Benz', modelName: 'EQC' },
  { brand: 'Mercedes-Benz', modelName: 'G-Class' },
  { brand: 'Mercedes-Benz', modelName: 'GL' },
  { brand: 'Mercedes-Benz', modelName: 'GLA' },
  { brand: 'Mercedes-Benz', modelName: 'GLB' },
  { brand: 'Mercedes-Benz', modelName: 'GLC' },
  { brand: 'Mercedes-Benz', modelName: 'GLE' },
  { brand: 'Mercedes-Benz', modelName: 'GLK' },
  { brand: 'Mercedes-Benz', modelName: 'GLS' },
  { brand: 'Mercedes-Benz', modelName: 'M-Class' },
  { brand: 'Mercedes-Benz', modelName: 'R-Class' },
  { brand: 'Mercedes-Benz', modelName: 'S-Class' },
  { brand: 'Mercedes-Benz', modelName: 'SL' },
  { brand: 'Mercedes-Benz', modelName: 'SLC' },
  { brand: 'Mercedes-Benz', modelName: 'SLK' },
  { brand: 'Mercedes-Benz', modelName: 'SLS' },
  { brand: 'Mercedes-Benz', modelName: 'SLR' },
  { brand: 'Mercedes-Benz', modelName: 'SLS AMG' },
  { brand: 'Mercedes-Benz', modelName: 'V-Class' },
  { brand: 'Mercedes-Benz', modelName: 'Vaneo' },
  { brand: 'Mercedes-Benz', modelName: 'Viano' },
  { brand: 'Mercedes-Benz', modelName: 'Vito' },
  { brand: 'Mercedes-Benz', modelName: 'X-Class' },
  { brand: 'Mercedes-Benz', modelName: 'ML' },
  { brand: 'Mercury', modelName: 'Capri' },
  { brand: 'Mercury', modelName: 'Comet' },
  { brand: 'Mercury', modelName: 'Cougar' },
  { brand: 'Mercury', modelName: 'Grand Marquis' },
  { brand: 'Mercury', modelName: 'Marauder' },
  { brand: 'Mercury', modelName: 'Milan' },
  { brand: 'Mercury', modelName: 'Montego' },
  { brand: 'Mercury', modelName: 'Monterey' },
  { brand: 'Mercury', modelName: 'Mountaineer' },
  { brand: 'Mercury', modelName: 'Mystique' },
  { brand: 'Mercury', modelName: 'Sable' },
  { brand: 'Mercury', modelName: 'Topaz' },
  { brand: 'Mercury', modelName: 'Tracer' },
  { brand: 'Mercury', modelName: 'Villager' },
  { brand: 'MG', modelName: '3' },
  { brand: 'MG', modelName: '5' },
  { brand: 'MG', modelName: '6' },
  { brand: 'MG', modelName: 'ZS' },
  { brand: 'MG', modelName: 'ZT' },
  { brand: 'Microcar', modelName: 'M.GO' },
  { brand: 'Mini', modelName: 'Cabrio' },
  { brand: 'Mini', modelName: 'Clubman' },
  { brand: 'Mini', modelName: 'Cooper' },
  { brand: 'Mini', modelName: 'Cooper S' },
  { brand: 'Mini', modelName: 'Countryman' },
  { brand: 'Mini', modelName: 'Coupe' },
  { brand: 'Mini', modelName: 'One' },
  { brand: 'Mini', modelName: 'Paceman' },
  { brand: 'Mitsubishi', modelName: '3000 GT' },
  { brand: 'Mitsubishi', modelName: 'ASX' },
  { brand: 'Mitsubishi', modelName: 'Carisma' },
  { brand: 'Mitsubishi', modelName: 'Colt' },
  { brand: 'Mitsubishi', modelName: 'Eclipse' },
  { brand: 'Mitsubishi', modelName: 'Eclipse Cross' },
  { brand: 'Mitsubishi', modelName: 'Endeavor' },
  { brand: 'Mitsubishi', modelName: 'i-MiEV' },
  { brand: 'Mitsubishi', modelName: 'Galant' },
  { brand: 'Mitsubishi', modelName: 'Grandis' },
  { brand: 'Mitsubishi', modelName: 'L200' },
  { brand: 'Mitsubishi', modelName: 'Lancer' },
  { brand: 'Mitsubishi', modelName: 'Mirage' },
  { brand: 'Mitsubishi', modelName: 'Lancer Evolution' },
  { brand: 'Mitsubishi', modelName: 'Outlander' },
  { brand: 'Mitsubishi', modelName: 'Pajero' },
  { brand: 'Mitsubishi', modelName: 'Pajero Pinin' },
  { brand: 'Mitsubishi', modelName: 'Pajero Sport' },
  { brand: 'Mitsubishi', modelName: 'Space Star' },
  { brand: 'Mitsubishi', modelName: 'Space Wagon' },
  { brand: 'Mitsubishi', modelName: 'Starion' },
  { brand: 'Mitsubishi', modelName: 'Triton' },
  { brand: 'Morgan', modelName: '3-Wheeler' },
  { brand: 'Morgan', modelName: '4/4' },
  { brand: 'Morgan', modelName: 'Aero 8' },
  { brand: 'Morgan', modelName: 'Aero SuperSports' },
  { brand: 'Morgan', modelName: 'Plus 4' },
  { brand: 'Morgan', modelName: 'Plus 6' },
  { brand: 'Morgan', modelName: 'Plus 8' },
  { brand: 'Nio', modelName: 'ES6' },
  { brand: 'Nio', modelName: 'ES8' },
  { brand: 'Nio', modelName: 'ET7' },
  { brand: 'Nissan', modelName: '100NX' },
  { brand: 'Nissan', modelName: '180SX' },
  { brand: 'Nissan', modelName: '200SX' },
  { brand: 'Nissan', modelName: '240SX' },
  { brand: 'Nissan', modelName: '300ZX' },
  { brand: 'Nissan', modelName: '350Z' },
  { brand: 'Nissan', modelName: '370Z' },
  { brand: 'Nissan', modelName: 'Almera' },
  { brand: 'Nissan', modelName: 'Altima' },
  { brand: 'Nissan', modelName: 'Cube' },
  { brand: 'Nissan', modelName: 'GT-R' },
  { brand: 'Nissan', modelName: 'Juke' },
  { brand: 'Nissan', modelName: 'Kubistar' },
  { brand: 'Nissan', modelName: 'Leaf' },
  { brand: 'Nissan', modelName: 'Maxima' },
  { brand: 'Nissan', modelName: 'Micra' },
  { brand: 'Nissan', modelName: 'Murano' },
  { brand: 'Nissan', modelName: 'Navara' },
  { brand: 'Nissan', modelName: 'Note' },
  { brand: 'Nissan', modelName: 'NP200' },
  { brand: 'Nissan', modelName: 'NP300' },
  { brand: 'Nissan', modelName: 'NV200' },
  { brand: 'Nissan', modelName: 'Pathfinder' },
  { brand: 'Nissan', modelName: 'Patrol' },
  { brand: 'Nissan', modelName: 'Primera' },
  { brand: 'Nissan', modelName: 'Pulsar' },
  { brand: 'Nissan', modelName: 'Qashqai' },
  { brand: 'Nissan', modelName: 'Quest' },
  { brand: 'Nissan', modelName: 'Silvia' },
  { brand: 'Nissan', modelName: 'Skyline' },
  { brand: 'Nissan', modelName: 'Sunny' },
  { brand: 'Nissan', modelName: 'Terrano' },
  { brand: 'Nissan', modelName: 'Tiida' },
  { brand: 'Nissan', modelName: 'Titan' },
  { brand: 'Nissan', modelName: 'X-Trail' },
  { brand: 'Nissan', modelName: 'Z' },
  { brand: 'Nissan', modelName: 'ARIYA' },
  { brand: 'Nissan', modelName: 'Townstar Combi/Van' },
  { brand: 'Nysa', modelName: '522' },
  { brand: 'Oldsmobile', modelName: '442' },
  { brand: 'Oldsmobile', modelName: 'Achieva' },
  { brand: 'Oldsmobile', modelName: 'Alero' },
  { brand: 'Oldsmobile', modelName: 'Aurora' },
  { brand: 'Oldsmobile', modelName: 'Bravada' },
  { brand: 'Oldsmobile', modelName: 'Cutlass' },
  { brand: 'Oldsmobile', modelName: 'Intrigue' },
  { brand: 'Oldsmobile', modelName: 'Silhouette' },
  { brand: 'Oldsmobile', modelName: 'Toronado' },
  { brand: 'Omoda', modelName: 'C5' },
  { brand: 'Omoda', modelName: 'E5' },
  { brand: 'Opel', modelName: 'Adam' },
  { brand: 'Opel', modelName: 'Agila' },
  { brand: 'Opel', modelName: 'Ampera' },
  { brand: 'Opel', modelName: 'Antara' },
  { brand: 'Opel', modelName: 'Astra' },
  { brand: 'Opel', modelName: 'Calibra' },
  { brand: 'Opel', modelName: 'Combo' },
  { brand: 'Opel', modelName: 'Corsa' },
  { brand: 'Opel', modelName: 'Crossland X' },
  { brand: 'Opel', modelName: 'Frontera' },
  { brand: 'Opel', modelName: 'Grandland X' },
  { brand: 'Opel', modelName: 'GT' },
  { brand: 'Opel', modelName: 'Insignia' },
  { brand: 'Opel', modelName: 'Karl' },
  { brand: 'Opel', modelName: 'Meriva' },
  { brand: 'Opel', modelName: 'Mokka' },
  { brand: 'Opel', modelName: 'Monterey' },
  { brand: 'Opel', modelName: 'Omega' },
  { brand: 'Opel', modelName: 'Signum' },
  { brand: 'Opel', modelName: 'Sintra' },
  { brand: 'Opel', modelName: 'Speedster' },
  { brand: 'Opel', modelName: 'Tigra' },
  { brand: 'Opel', modelName: 'Vectra' },
  { brand: 'Opel', modelName: 'Vivaro' },
  { brand: 'Opel', modelName: 'Zafira' },
  { brand: 'Peugeot', modelName: '1007' },
  { brand: 'Peugeot', modelName: '106' },
  { brand: 'Peugeot', modelName: '107' },
  { brand: 'Peugeot', modelName: '108' },
  { brand: 'Peugeot', modelName: '2008' },
  { brand: 'Peugeot', modelName: '205' },
  { brand: 'Peugeot', modelName: '206' },
  { brand: 'Peugeot', modelName: '207' },
  { brand: 'Peugeot', modelName: '208' },
  { brand: 'Peugeot', modelName: '3008' },
  { brand: 'Peugeot', modelName: '301' },
  { brand: 'Peugeot', modelName: '304' },
  { brand: 'Peugeot', modelName: '305' },
  { brand: 'Peugeot', modelName: '306' },
  { brand: 'Peugeot', modelName: '307' },
  { brand: 'Peugeot', modelName: '308' },
  { brand: 'Peugeot', modelName: '4007' },
  { brand: 'Peugeot', modelName: '4008' },
  { brand: 'Peugeot', modelName: '404' },
  { brand: 'Peugeot', modelName: '405' },
  { brand: 'Peugeot', modelName: '406' },
  { brand: 'Peugeot', modelName: '407' },
  { brand: 'Peugeot', modelName: '408' },
  { brand: 'Peugeot', modelName: '504' },
  { brand: 'Peugeot', modelName: '505' },
  { brand: 'Peugeot', modelName: '5008' },
  { brand: 'Peugeot', modelName: '508' },
  { brand: 'Peugeot', modelName: '604' },
  { brand: 'Peugeot', modelName: '605' },
  { brand: 'Peugeot', modelName: '607' },
  { brand: 'Peugeot', modelName: '806' },
  { brand: 'Peugeot', modelName: '807' },
  { brand: 'Peugeot', modelName: 'Bipper' },
  { brand: 'Peugeot', modelName: 'Boxer' },
  { brand: 'Peugeot', modelName: 'iOn' },
  { brand: 'Peugeot', modelName: 'Expert' },
  { brand: 'Peugeot', modelName: 'Partner' },
  { brand: 'Peugeot', modelName: 'RCZ' },
  { brand: 'Peugeot', modelName: 'Rifter/Traveler' },
  { brand: 'Piaggio', modelName: 'Porter' },
  { brand: 'Piaggio', modelName: 'Vespa 400' },
  { brand: 'Piaggio', modelName: 'Ape Car' },
  { brand: 'Plymouth', modelName: 'Acclaim' },
  { brand: 'Plymouth', modelName: 'Barracuda' },
  { brand: 'Plymouth', modelName: 'Belvedere' },
  { brand: 'Plymouth', modelName: 'Colt' },
  { brand: 'Plymouth', modelName: 'Fury' },
  { brand: 'Plymouth', modelName: 'Gran Fury' },
  { brand: 'Plymouth', modelName: 'GTX' },
  { brand: 'Plymouth', modelName: 'Horizon' },
  { brand: 'Plymouth', modelName: 'Neon' },
  { brand: 'Plymouth', modelName: 'Prowler' },
  { brand: 'Plymouth', modelName: 'Road Runner' },
  { brand: 'Plymouth', modelName: 'Satellite' },
  { brand: 'Plymouth', modelName: 'Superbird' },
  { brand: 'Plymouth', modelName: 'Valiant' },
  { brand: 'Plymouth', modelName: 'Voyager' },
  { brand: 'Polestar', modelName: '1' },
  { brand: 'Polestar', modelName: '2' },
  { brand: 'Polestar', modelName: '3' },
  { brand: 'Polestar', modelName: '4' },
  { brand: 'Polestar', modelName: '5' },
  { brand: 'Polestar', modelName: 'Precept' },
  { brand: 'Polonez', modelName: 'Atu' },
  { brand: 'Polonez', modelName: 'Atu Plus' },
  { brand: 'Polonez', modelName: 'Caro' },
  { brand: 'Polonez', modelName: 'Caro Plus' },
  { brand: 'Polonez', modelName: 'Cargo' },
  { brand: 'Polonez', modelName: 'Truck' },
  { brand: 'Polonez', modelName: 'Kombi' },
  { brand: 'Polonez', modelName: 'Hatchback' },
  { brand: 'Pontiac', modelName: 'Aztek' },
  { brand: 'Pontiac', modelName: 'Bonneville' },
  { brand: 'Pontiac', modelName: 'Catalina' },
  { brand: 'Pontiac', modelName: 'Fiero' },
  { brand: 'Pontiac', modelName: 'Firebird' },
  { brand: 'Pontiac', modelName: 'G5' },
  { brand: 'Pontiac', modelName: 'G6' },
  { brand: 'Pontiac', modelName: 'G8' },
  { brand: 'Pontiac', modelName: 'Grand Am' },
  { brand: 'Pontiac', modelName: 'Grand Prix' },
  { brand: 'Pontiac', modelName: 'GTO' },
  { brand: 'Pontiac', modelName: 'LeMans' },
  { brand: 'Pontiac', modelName: 'Montana' },
  { brand: 'Pontiac', modelName: 'Solstice' },
  { brand: 'Pontiac', modelName: 'Sunbird' },
  { brand: 'Pontiac', modelName: 'Sunfire' },
  { brand: 'Pontiac', modelName: 'Tempest' },
  { brand: 'Pontiac', modelName: 'Torrent' },
  { brand: 'Pontiac', modelName: 'Trans Sport' },
  { brand: 'Pontiac', modelName: 'Vibe' },
  { brand: 'Porsche', modelName: '356' },
  { brand: 'Porsche', modelName: '911' },
  { brand: 'Porsche', modelName: '912' },
  { brand: 'Porsche', modelName: '914' },
  { brand: 'Porsche', modelName: '918 Spyder' },
  { brand: 'Porsche', modelName: '924' },
  { brand: 'Porsche', modelName: '928' },
  { brand: 'Porsche', modelName: '930' },
  { brand: 'Porsche', modelName: '944' },
  { brand: 'Porsche', modelName: '959' },
  { brand: 'Porsche', modelName: '964' },
  { brand: 'Porsche', modelName: '968' },
  { brand: 'Porsche', modelName: 'Boxster' },
  { brand: 'Porsche', modelName: 'Carrera GT' },
  { brand: 'Porsche', modelName: 'Cayenne' },
  { brand: 'Porsche', modelName: 'Cayman' },
  { brand: 'Porsche', modelName: 'Macan' },
  { brand: 'Porsche', modelName: 'Panamera' },
  { brand: 'Porsche', modelName: 'Taycan' },
  { brand: 'RAM', modelName: '1500' },
  { brand: 'RAM', modelName: '2500' },
  { brand: 'RAM', modelName: '3500' },
  { brand: 'RAM', modelName: '4500' },
  { brand: 'RAM', modelName: '5500' },
  { brand: 'Renault', modelName: '2' },
  { brand: 'Renault', modelName: '3' },
  { brand: 'Renault', modelName: '4' },
  { brand: 'Renault', modelName: '5' },
  { brand: 'Renault', modelName: '9' },
  { brand: 'Renault', modelName: '11' },
  { brand: 'Renault', modelName: '12' },
  { brand: 'Renault', modelName: '14' },
  { brand: 'Renault', modelName: '16' },
  { brand: 'Renault', modelName: '18' },
  { brand: 'Renault', modelName: '19' },
  { brand: 'Renault', modelName: '20' },
  { brand: 'Renault', modelName: '21' },
  { brand: 'Renault', modelName: '25' },
  { brand: 'Renault', modelName: '4CV' },
  { brand: 'Renault', modelName: 'Avantime' },
  { brand: 'Renault', modelName: 'Captur' },
  { brand: 'Renault', modelName: 'Clio' },
  { brand: 'Renault', modelName: 'Duster' },
  { brand: 'Renault', modelName: 'Espace' },
  { brand: 'Renault', modelName: 'Fluence' },
  { brand: 'Renault', modelName: 'Fuego' },
  { brand: 'Renault', modelName: 'Kadjar' },
  { brand: 'Renault', modelName: 'Kangoo' },
  { brand: 'Renault', modelName: 'Koleos' },
  { brand: 'Renault', modelName: 'Laguna' },
  { brand: 'Renault', modelName: 'Latitude' },
  { brand: 'Renault', modelName: 'Lodgy' },
  { brand: 'Renault', modelName: 'Logan' },
  { brand: 'Renault', modelName: 'Megane' },
  { brand: 'Renault', modelName: 'Modus' },
  { brand: 'Renault', modelName: 'Rodeo' },
  { brand: 'Renault', modelName: 'Safrane' },
  { brand: 'Renault', modelName: 'Scenic' },
  { brand: 'Renault', modelName: 'Sport Spider' },
  { brand: 'Renault', modelName: 'Supercinq' },
  { brand: 'Renault', modelName: 'Talisman' },
  { brand: 'Renault', modelName: 'Thalia' },
  { brand: 'Renault', modelName: 'Trafic' },
  { brand: 'Renault', modelName: 'Twingo' },
  { brand: 'Renault', modelName: 'Twizy' },
  { brand: 'Renault', modelName: 'Vel Satis' },
  { brand: 'Renault', modelName: 'Wind' },
  { brand: 'Renault', modelName: 'Zoe' },
  { brand: 'Rolls-Royce', modelName: 'Corniche' },
  { brand: 'Rolls-Royce', modelName: 'Cullinan' },
  { brand: 'Rolls-Royce', modelName: 'Dawn' },
  { brand: 'Rolls-Royce', modelName: 'Ghost' },
  { brand: 'Rolls-Royce', modelName: 'Phantom' },
  { brand: 'Rolls-Royce', modelName: 'Silver Cloud' },
  { brand: 'Rolls-Royce', modelName: 'Silver Seraph' },
  { brand: 'Rolls-Royce', modelName: 'Silver Shadow' },
  { brand: 'Rolls-Royce', modelName: 'Silver Spirit' },
  { brand: 'Rolls-Royce', modelName: 'Silver Wraith' },
  { brand: 'Rolls-Royce', modelName: 'Wraith' },
  { brand: 'Rover', modelName: '200' },
  { brand: 'Rover', modelName: '25' },
  { brand: 'Rover', modelName: '400' },
  { brand: 'Rover', modelName: '45' },
  { brand: 'Rover', modelName: '600' },
  { brand: 'Rover', modelName: '75' },
  { brand: 'Rover', modelName: '800' },
  { brand: 'Rover', modelName: 'CityRover' },
  { brand: 'Rover', modelName: 'Metro' },
  { brand: 'Rover', modelName: 'Streetwise' },
  { brand: 'Saab', modelName: '9-2X' },
  { brand: 'Saab', modelName: '9-3' },
  { brand: 'Saab', modelName: '9-4X' },
  { brand: 'Saab', modelName: '9-5' },
  { brand: 'Saab', modelName: '9-7X' },
  { brand: 'Saturn', modelName: 'Aura' },
  { brand: 'Saturn', modelName: 'Ion' },
  { brand: 'Saturn', modelName: 'L-Series' },
  { brand: 'Saturn', modelName: 'Outlook' },
  { brand: 'Saturn', modelName: 'Relay' },
  { brand: 'Saturn', modelName: 'S-Series' },
  { brand: 'Saturn', modelName: 'Sky' },
  { brand: 'Saturn', modelName: 'Vue' },
  { brand: 'SEAT', modelName: 'Alhambra' },
  { brand: 'SEAT', modelName: 'Altea' },
  { brand: 'SEAT', modelName: 'Arona' },
  { brand: 'SEAT', modelName: 'Arosa' },
  { brand: 'SEAT', modelName: 'Ateca' },
  { brand: 'SEAT', modelName: 'Cordoba' },
  { brand: 'SEAT', modelName: 'Exeo' },
  { brand: 'SEAT', modelName: 'Ibiza' },
  { brand: 'SEAT', modelName: 'Leon' },
  { brand: 'SEAT', modelName: 'Mii' },
  { brand: 'SEAT', modelName: 'Tarraco' },
  { brand: 'SEAT', modelName: 'Toledo' },
  { brand: 'Seres', modelName: 'SF5' },
  { brand: 'Seres', modelName: 'SF7' },
  { brand: 'Shuanghuan', modelName: 'CEO' },
  { brand: 'Shuanghuan', modelName: 'Noble' },
  { brand: 'Skoda', modelName: 'Citigo' },
  { brand: 'Skoda', modelName: 'Enyaq' },
  { brand: 'Skoda', modelName: 'Fabia' },
  { brand: 'Skoda', modelName: 'Felicia' },
  { brand: 'Skoda', modelName: 'Kamiq' },
  { brand: 'Skoda', modelName: 'Karoq' },
  { brand: 'Skoda', modelName: 'Kodiaq' },
  { brand: 'Skoda', modelName: 'Octavia' },
  { brand: 'Skoda', modelName: 'Rapid' },
  { brand: 'Skoda', modelName: 'Roomster' },
  { brand: 'Skoda', modelName: 'Scala' },
  { brand: 'Skoda', modelName: 'Superb' },
  { brand: 'Skoda', modelName: 'Yeti' },
  { brand: 'Skywell', modelName: 'ET5' },
  { brand: 'Skywell', modelName: 'ET6' },
  { brand: 'Smart', modelName: 'Forfour' },
  { brand: 'Smart', modelName: 'Fortwo' },
  { brand: 'Smart', modelName: 'Roadster' },
  { brand: 'SsangYong', modelName: 'Actyon' },
  { brand: 'SsangYong', modelName: 'Korando' },
  { brand: 'SsangYong', modelName: 'Kyron' },
  { brand: 'SsangYong', modelName: 'Musso' },
  { brand: 'SsangYong', modelName: 'Rexton' },
  { brand: 'SsangYong', modelName: 'Rodius' },
  { brand: 'SsangYong', modelName: 'Tivoli' },
  { brand: 'SsangYong', modelName: 'XLV' },
  { brand: 'Subaru', modelName: 'BRZ' },
  { brand: 'Subaru', modelName: 'Forester' },
  { brand: 'Subaru', modelName: 'Impreza' },
  { brand: 'Subaru', modelName: 'Justy' },
  { brand: 'Subaru', modelName: 'Legacy' },
  { brand: 'Subaru', modelName: 'Leone' },
  { brand: 'Subaru', modelName: 'Outback' },
  { brand: 'Subaru', modelName: 'XV' },
  { brand: 'Subaru', modelName: 'SVX' },
  { brand: 'Subaru', modelName: 'Tribeca' },
  { brand: 'Subaru', modelName: 'Vivio' },
  { brand: 'Subaru', modelName: 'WRX' },
  { brand: 'Subaru', modelName: 'Solterra' },
  { brand: 'Suzuki', modelName: 'Alto' },
  { brand: 'Suzuki', modelName: 'Baleno' },
  { brand: 'Suzuki', modelName: 'Grand Vitara' },
  { brand: 'Suzuki', modelName: 'Ignis' },
  { brand: 'Suzuki', modelName: 'Jimny' },
  { brand: 'Suzuki', modelName: 'Kizashi' },
  { brand: 'Suzuki', modelName: 'Liana' },
  { brand: 'Suzuki', modelName: 'Splash' },
  { brand: 'Suzuki', modelName: 'Samurai' },
  { brand: 'Suzuki', modelName: 'Swift' },
  { brand: 'Suzuki', modelName: 'SX4' },
  { brand: 'Suzuki', modelName: 'Vitara' },
  { brand: 'Suzuki', modelName: 'Wagon R' },
  { brand: 'Suzuki', modelName: 'XL7' },
  { brand: 'Suzuki', modelName: 'S-cross' },
  { brand: 'Suzuki', modelName: 'Swace' },
  { brand: 'Syrena', modelName: '105' },
  { brand: 'Syrena', modelName: 'GTE' },
  { brand: 'Syrena', modelName: '104' },
  { brand: 'Tarpan', modelName: 'Honker' },
  { brand: 'Tata', modelName: 'Altroz' },
  { brand: 'Tata', modelName: 'Harrier' },
  { brand: 'Tata', modelName: 'Nexon' },
  { brand: 'Tata', modelName: 'Safari' },
  { brand: 'Tata', modelName: 'Sierra' },
  { brand: 'Tata', modelName: 'Sumo' },
  { brand: 'Tata', modelName: 'Tiago' },
  { brand: 'Tata', modelName: 'Tigor' },
  { brand: 'Tata', modelName: 'Xenon' },
  { brand: 'Tesla', modelName: 'modelName 3' },
  { brand: 'Tesla', modelName: 'modelName S' },
  { brand: 'Tesla', modelName: 'modelName X' },
  { brand: 'Tesla', modelName: 'modelName Y' },
  { brand: 'Tesla', modelName: 'Roadster' },
  { brand: 'Toyota', modelName: '4Runner' },
  { brand: 'Toyota', modelName: 'Auris' },
  { brand: 'Toyota', modelName: 'Avalon' },
  { brand: 'Toyota', modelName: 'Avensis' },
  { brand: 'Toyota', modelName: 'Avensis Verso' },
  { brand: 'Toyota', modelName: 'Aygo' },
  { brand: 'Toyota', modelName: 'C-HR' },
  { brand: 'Toyota', modelName: 'Camry' },
  { brand: 'Toyota', modelName: 'Solara' },
  { brand: 'Toyota', modelName: 'Carina' },
  { brand: 'Toyota', modelName: 'Celica' },
  { brand: 'Toyota', modelName: 'Corolla' },
  { brand: 'Toyota', modelName: 'Corolla Verso' },
  { brand: 'Toyota', modelName: 'FJ Cruiser' },
  { brand: 'Toyota', modelName: 'GT 86' },
  { brand: 'Toyota', modelName: 'Hiace' },
  { brand: 'Toyota', modelName: 'Highlander' },
  { brand: 'Toyota', modelName: 'Hilux' },
  { brand: 'Toyota', modelName: 'Land Cruiser' },
  { brand: 'Toyota', modelName: 'Land Cruiser Prado' },
  { brand: 'Toyota', modelName: 'MR2' },
  { brand: 'Toyota', modelName: 'Paseo' },
  { brand: 'Toyota', modelName: 'Picnic' },
  { brand: 'Toyota', modelName: 'Previa' },
  { brand: 'Toyota', modelName: 'Prius' },
  { brand: 'Toyota', modelName: 'RAV4' },
  { brand: 'Toyota', modelName: 'Sequoia' },
  { brand: 'Toyota', modelName: 'Sienna' },
  { brand: 'Toyota', modelName: 'Soarer' },
  { brand: 'Toyota', modelName: 'Starlet' },
  { brand: 'Toyota', modelName: 'Supra' },
  { brand: 'Toyota', modelName: 'Tacoma' },
  { brand: 'Toyota', modelName: 'Tercel' },
  { brand: 'Toyota', modelName: 'Tundra' },
  { brand: 'Toyota', modelName: 'Urban Cruiser' },
  { brand: 'Toyota', modelName: 'Verso' },
  { brand: 'Toyota', modelName: 'Yaris' },
  { brand: 'Toyota', modelName: 'Yaris Cross' },
  { brand: 'Toyota', modelName: 'Yaris Verso' },
  { brand: 'Toyota', modelName: 'Proace' },
  { brand: 'Trabant', modelName: '601' },
  { brand: 'Triumph', modelName: 'Dolomite' },
  { brand: 'Triumph', modelName: 'GT6' },
  { brand: 'Triumph', modelName: 'Herald' },
  { brand: 'Triumph', modelName: 'Spitfire' },
  { brand: 'Triumph', modelName: 'Stag' },
  { brand: 'Triumph', modelName: 'TR2' },
  { brand: 'Triumph', modelName: 'TR3' },
  { brand: 'Triumph', modelName: 'TR4' },
  { brand: 'Triumph', modelName: 'TR5' },
  { brand: 'Triumph', modelName: 'TR6' },
  { brand: 'Triumph', modelName: 'TR7' },
  { brand: 'Triumph', modelName: 'TR8' },
  { brand: 'UAZ', modelName: '3151' },
  { brand: 'UAZ', modelName: '469' },
  { brand: 'UAZ', modelName: '452' },
  { brand: 'Vauxhall', modelName: 'Adam' },
  { brand: 'Vauxhall', modelName: 'Agila' },
  { brand: 'Vauxhall', modelName: 'Ampera' },
  { brand: 'Vauxhall', modelName: 'Antara' },
  { brand: 'Vauxhall', modelName: 'Astra' },
  { brand: 'Vauxhall', modelName: 'Calibra' },
  { brand: 'Vauxhall', modelName: 'Carlton' },
  { brand: 'Vauxhall', modelName: 'Cavalier' },
  { brand: 'Vauxhall', modelName: 'Chevette' },
  { brand: 'Vauxhall', modelName: 'Combo' },
  { brand: 'Vauxhall', modelName: 'Corsa' },
  { brand: 'Vauxhall', modelName: 'Frontera' },
  { brand: 'Vauxhall', modelName: 'Insignia' },
  { brand: 'Vauxhall', modelName: 'Meriva' },
  { brand: 'Vauxhall', modelName: 'Mokka' },
  { brand: 'Vauxhall', modelName: 'Monaro' },
  { brand: 'Vauxhall', modelName: 'Movano' },
  { brand: 'Vauxhall', modelName: 'Nova' },
  { brand: 'Vauxhall', modelName: 'Omega' },
  { brand: 'Vauxhall', modelName: 'Signum' },
  { brand: 'Vauxhall', modelName: 'Sintra' },
  { brand: 'Vauxhall', modelName: 'Vectra' },
  { brand: 'Vauxhall', modelName: 'Viceroy' },
  { brand: 'Vauxhall', modelName: 'Victor' },
  { brand: 'Vauxhall', modelName: 'Viva' },
  { brand: 'Vauxhall', modelName: 'Vivaro' },
  { brand: 'Vauxhall', modelName: 'VX220' },
  { brand: 'Vauxhall', modelName: 'VXR8' },
  { brand: 'Vauxhall', modelName: 'Zafira' },
  { brand: 'Volkswagen', modelName: 'Amarok' },
  { brand: 'Volkswagen', modelName: 'Arteon' },
  { brand: 'Volkswagen', modelName: 'Beetle' },
  { brand: 'Volkswagen', modelName: 'Bora' },
  { brand: 'Volkswagen', modelName: 'Caddy' },
  { brand: 'Volkswagen', modelName: 'California' },
  { brand: 'Volkswagen', modelName: 'Caravelle' },
  { brand: 'Volkswagen', modelName: 'Corrado' },
  { brand: 'Volkswagen', modelName: 'Eos' },
  { brand: 'Volkswagen', modelName: 'Fox' },
  { brand: 'Volkswagen', modelName: 'Golf' },
  { brand: 'Volkswagen', modelName: 'Jetta' },
  { brand: 'Volkswagen', modelName: 'Lupo' },
  { brand: 'Volkswagen', modelName: 'Multivan' },
  { brand: 'Volkswagen', modelName: 'Passat' },
  { brand: 'Volkswagen', modelName: 'Passat CC' },
  { brand: 'Volkswagen', modelName: 'Phaeton' },
  { brand: 'Volkswagen', modelName: 'Polo' },
  { brand: 'Volkswagen', modelName: 'Routan' },
  { brand: 'Volkswagen', modelName: 'Scirocco' },
  { brand: 'Volkswagen', modelName: 'Sharan' },
  { brand: 'Volkswagen', modelName: 'Suran' },
  { brand: 'Volkswagen', modelName: 'T-Cross' },
  { brand: 'Volkswagen', modelName: 'T-Roc' },
  { brand: 'Volkswagen', modelName: 'Tiguan' },
  { brand: 'Volkswagen', modelName: 'Touareg' },
  { brand: 'Volkswagen', modelName: 'Touran' },
  { brand: 'Volkswagen', modelName: 'Transporter' },
  { brand: 'Volkswagen', modelName: 'Up' },
  { brand: 'Volkswagen', modelName: 'Vento' },
  { brand: 'Volkswagen', modelName: 'Taigo' },
  { brand: 'Volkswagen', modelName: 'ID4' },
  { brand: 'Volkswagen', modelName: 'ID5' },
  { brand: 'Volvo', modelName: '240' },
  { brand: 'Volvo', modelName: '260' },
  { brand: 'Volvo', modelName: '340' },
  { brand: 'Volvo', modelName: '360' },
  { brand: 'Volvo', modelName: '440' },
  { brand: 'Volvo', modelName: '460' },
  { brand: 'Volvo', modelName: '480' },
  { brand: 'Volvo', modelName: '740' },
  { brand: 'Volvo', modelName: '760' },
  { brand: 'Volvo', modelName: '780' },
  { brand: 'Volvo', modelName: '850' },
  { brand: 'Volvo', modelName: '940' },
  { brand: 'Volvo', modelName: '960' },
  { brand: 'Volvo', modelName: 'C30' },
  { brand: 'Volvo', modelName: 'C70' },
  { brand: 'Volvo', modelName: 'S40' },
  { brand: 'Volvo', modelName: 'S60' },
  { brand: 'Volvo', modelName: 'S70' },
  { brand: 'Volvo', modelName: 'S80' },
  { brand: 'Volvo', modelName: 'S90' },
  { brand: 'Volvo', modelName: 'V40' },
  { brand: 'Volvo', modelName: 'V50' },
  { brand: 'Volvo', modelName: 'V60' },
  { brand: 'Volvo', modelName: 'V70' },
  { brand: 'Volvo', modelName: 'V90' },
  { brand: 'Volvo', modelName: 'XC40' },
  { brand: 'Volvo', modelName: 'XC60' },
  { brand: 'Volvo', modelName: 'XC70' },
  { brand: 'Volvo', modelName: 'XC90' },
  { brand: 'Voyah', modelName: 'Free' },
  { brand: 'Voyah', modelName: 'i' },
  { brand: 'Voyah', modelName: 'Mars' },
  { brand: 'Voyah', modelName: 'S' },
  { brand: 'Voyah', modelName: 'Y' },
  { brand: 'Warszawa', modelName: 'M20' },
  { brand: 'Wartburg', modelName: '311' },
  { brand: 'Wartburg', modelName: '353' },
  { brand: 'Wartburg', modelName: '1.3' },
  { brand: 'Wołga', modelName: '21' },
  { brand: 'Wołga', modelName: '24' },
  { brand: 'Wołga', modelName: '24-10' },
  { brand: 'Wołga', modelName: '3102' },
  { brand: 'Zaporożec', modelName: '965' },
  { brand: 'Zaporożec', modelName: '966' },
  { brand: 'Zaporożec', modelName: '968' },
  { brand: 'Zaporożec', modelName: '968A' },
  { brand: 'Zastava', modelName: '101' },
  { brand: 'Zastava', modelName: '128' },
  { brand: 'Zastava', modelName: '1300' },
  { brand: 'Zastava', modelName: '600' },
  { brand: 'Zastava', modelName: '750' },
  { brand: 'Zastava', modelName: 'Florida' },
  { brand: 'Zastava', modelName: 'Yugo' },
  { brand: 'ZEEKR', modelName: '001' },
  { brand: 'ŻUK', modelName: 'A-03' },
  { brand: 'ŻUK', modelName: 'A-06' },
  { brand: 'ŻUK', modelName: 'A-07' },
  { brand: 'ŻUK', modelName: 'A-08' },
  { brand: 'ŻUK', modelName: 'A-09' },
];

export async function seedVehicleModels() {
  try {
    const result = await prisma.vehicleModel.createMany({
      data: vehicleModels,
      skipDuplicates: true,
    });

    console.log('Successfully seeded vehicle models:', result.count);
  } catch (error) {
    console.error('Error seeding vehicle models:', error);
    throw error;
  }
}

if (require.main === module) {
  seedVehicleModels()
    .then(async () => {
      await prisma.$disconnect();
    })

    .catch(async (e) => {
      console.error(e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
