import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const vehicleBrands = [
  'Abarth',
  'Acura',
  'Aixam',
  'Alfa Romeo',
  'Alpine',
  'Asia',
  'Aston Martin',
  'Audi',
  'Austin',
  'Autobianchi',
  'Baic',
  'Bentley',
  'BMW',
  'BMW-ALPINA',
  'Brilliance',
  'Bugatti',
  'Buick',
  'Cadillac',
  'Casalini',
  'Caterham',
  'Chatenet',
  'Chevrolet',
  'Chrysler',
  'Citroen',
  'Cupra',
  'Dacia',
  'Daewoo',
  'Daihatsu',
  'DeLorean',
  'DFM',
  'DKW',
  'Dodge',
  'DS Automobiles',
  'Elaris',
  'FAW',
  'Ferrari',
  'Fiat',
  'Ford',
  'Gaz',
  'Geely',
  'Genesis',
  'GMC',
  'GWM',
  'Honda',
  'Hongqi',
  'Hummer',
  'Hyundai',
  'Ineos',
  'Infinity',
  'Isuzu',
  'Iveco',
  'Jaguar',
  'Jeep',
  'Kia',
  'KTM',
  'Lada',
  'Lamborghini',
  'Lancia',
  'Leapmotor',
  'LEVC',
  'Land Rover',
  'Lexus',
  'Ligier',
  'Lincoln',
  'Lixiang',
  'Lotus',
  'LTI',
  'Lucid',
  'Lynk & Co',
  'MAN',
  'Maserati',
  'MAXIMUS',
  'Maxus',
  'Maybach',
  'Mazda',
  'McLaren',
  'Mercedes-Benz',
  'Mercury',
  'MG',
  'Microcar',
  'MINI',
  'Mitsubishi',
  'Morgan',
  'Nio',
  'Nissan',
  'Nysa',
  'Oldsmobile',
  'Omoda',
  'Opel',
  'Peugeot',
  'Piaggio',
  'Plymouth',
  'Polestar',
  'Polonez',
  'Pontiac',
  'Porsche',
  'RAM',
  'Renault',
  'Rolls-Royce',
  'Rover',
  'Saab',
  'Saturn',
  'SEAT',
  'Seres',
  'Shuanghuan',
  'Skoda',
  'Skywell',
  'Smart',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Syrena',
  'Tarpan',
  'Tata',
  'Tesla',
  'Toyota',
  'Trabant',
  'Triumph',
  'UAZ',
  'Vauxhall',
  'Volkswagen',
  'Volvo',
  'Voyah',
  'Warszawa',
  'Wartburg',
  'Wołga',
  'Zaporożec',
  'Zastava',
  'ZEEKR',
  'ŻUK',
].map((brandName) => ({ brandName }));

export async function seedVehicleBrands() {
  try {
    const result = await prisma.vehicleBrand.createMany({
      data: vehicleBrands,
      skipDuplicates: true,
    });

    console.log('Successfully seeded vehicle brands:', result.count);
  } catch (error) {
    console.error('Error seeding vehicle brands:', error);
    throw error;
  }
}

if (require.main === module) {
  seedVehicleBrands()
    .then(async () => {
      await prisma.$disconnect();
    })
    .catch(async (e) => {
      console.error(e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
